************************************************************************
* Program:  Label_ownerpt.sas
* Library:  RealProp
* Project:  DC Data Warehouse
* Author:   P. Tatian
* Created:  7/20/04
* Version:  SAS 8.12
* Environment:  PC
* 
* Description:  Label variables in OWNERPT file
*
* Modifications:
    04/14/05  Added labels for X_COORD, Y_COORD, Class_Type_3d,
              Mix1class_3d, Mix2class_3d.
    04/22/05  Revised and added labels for tax fields
    06/09/05  Added label for PREMISEZIP
    11/02/09  PAT Added label for MIXEDUSE_NEW
	06/24/22  RP Updated for new variables from DC Open Data
************************************************************************;

label
  Ssl = "Property Identification Number (Square/Suffix/Lot)"
  Square = "Square map number property is found on, may also be PAR or RES or RT"
  Suffix = "Typically N, S, E, W modifier to Square, when Square is PAR suffix is the map number"
  Lot = "Lot number of the property (unique within Square/Suffix)"
  Arn = "Assessor Identification Number"
  Asr_name = "Assessor's Name"
  Proptype = "Type of property"
  Trigroup = "Triennial Tax Assessment Group assignment"
  Usecode = "Property Use Codes"
  Landarea = "Square footage of property from the recorded deed"
  Premiseadd = "Property street address excluding city & zipcode"
  PRMS_WARD = "Property ward [from Ownerpt file]"
  Nbhd = "Assessor's Neighborhood code"
  Nbhdname = "Assessor's neighborhood name"
  Sub_nbhd = "Assessor's sub-neighborhood code"
  Unitnumber = "Unit number, typically associated with condominiums"
  Ownername = "Property owner's name"
  ownname2 = "2nd property owner's name"
  Careofname = "Name to whom the tax bill is sent"
  Address1 = "Tax billing address part 1"
  Address2 = "Tax billing address part 2"
  Address3 = "Tax billing address part 3 (City, State, ZIP)"
  Reasoncode = "Reason for Assessment Change"
  Old_land = "Prior appraised land value"
  Old_impr = "Prior appraised value of improvements such as buildings"
  Old_total = "Total Prior appraised value of land and improvements"
  New_land = "Current appraised land value"
  New_impr = "Current appraised value of improvements such as buildings"
  New_total = "Total Current appraised value of land and improvements"
  Phaseland = "Current Phase-In Land Assessment"
  Phasebuild = "Current Phase-In Building  Assessment"
  Part_part = "Flag to indicate lot has two tax types"
  Vaclnduse = "Vacant Land Use"
  Lownumber = "Base House Number of the property address"
  Highnumber = "Ending House number of the property if it includes multiple addresses"
  Streetname = "Street name portion of the property address"
  Qdrntname = "Quadrant name spelled out: NE,NW,SE or SW"
  Del_code = "Flag for inactive records"
  Hstd_code = "Homestead flag"
  Mix1txtype = "First Tax type"
  Mix1class = "First Tax Class"
  Mix1rate = "Tax rate applied for first Use type"
  Mix1lndpct = "Percentage of the land considered to be first landuse type"
  Mix1lndval = "Proportioned amount of the land value to be taxed at mix1rate"
  Mix1bldpct = "Percentage of the improvement considered to be first landuse type"
  Mix1bldval = "Proportioned amount of the improvement value to be taxed at mix1rate"
  Mix2txtype = "Second Tax Type"
  Mix2class = "Second Tax Class"
  Mix2rate = "Tax rate applied for second landuse type"
  Mix2lndpct = "Percentage of the land considered to be second landuse type"
  Mix2lndval = "Proportioned amount of the land value to be taxed at mix2rate"
  Mix2bldpct = "Percentage of the improvement considered to be second landuse type"
  Mix2bldval = "Proportioned amount of the improvement value to be taxed at mix2rate"
  Class_Type_3d = "Tax Class (new 3-digit codes)"
  Mix1class_3d = "First Tax Class (new 3-digit codes)" 
  Mix2class_3d = "Second Tax Class (new 3-digit codes)"
  No_ownocct = "Number of occupied cooperative units"
  No_units = "Number of available cooperative units"
  Pchildcode = "Use code of child property"
  Abtlotcode = "SSL of the abutting property"
  Saleprice = "Most recent property sale price"
  Saledate = "Most recent property sale date"
  Inst_no = "Instrument number for last property or ownership modification"
  Acceptcode = "Property sale acceptance code"
  Acceptcode_new = "Property sale acceptance code (new 2005 code)"
  Saletype = "Type of property sale"
  Saletype_new = "Type of property sale (new 2005 code)"
  Deed_date = "Date of deed"
  Mortgageco = "Mortgage Key Number"
  Assess_val = "Current Assessed Value Total: Total of phaseland and phasebuild"
  Tax_rate = "Current tax rate for this record"
  Amttax = "Current amount of annual tax"
  Duedate1 = "Bill Due date 1"
  Amtdue1 = "Bill amount due1"
  Duedate2 = "Bill due date 2"
  Amtdue2 = "Bill amount due 2"
  Duedate3 = "Bill due date 3"
  Amtdue3 = "Bill amount due 3"
  OWNERPT_EXTRACTDAT = "Date of database extraction [OWNERPT]"
  CAPASSCUR = "CAP Assessment for Current Year"
  CAPASSPRO = "CAP Assessment for Proposed Year"
  x_coord = "Longitude of parcel center (MD State Plane Coord., NAD 1983 meters)"
  y_coord = "Latitude of parcel center (MD State Plane Coord., NAD 1983 meters)"

  nmixeduse = "Indicates whether multiple property uses are present for taxation purposes"
  ndelcode = "Deletion code (numeric)"
  npartpart = "Numeric version of PARTPART"
  saletype_old = "Type of property sale (old code)"

  /* Labels from DC Open data portal January 2021 */
	ABTLOTCODE	="SSL of the abutting property"
	ACCEPTCODE	="Property sale acceptance code"
	ADDRESS1	="Tax billing address part 1"
	ADDRESS2	="Tax billing address part 2"
	AMTDUE1	="Bill amount due at first due date"
	AMTDUE2	="Bill amount due at second due date"
	AMTDUE3	="Bill amount due at third due date"
	ARN	="Assessor ID Number"
	ASR_NAME	="Name of property assessor"
	CAPASSCUR	="Cap assessment for current year"
	CAPASSPRO	="Cap assessment for proposed year"
	CAREOFNAME	="Name to whom the tax bill is sent"
	CY1BAL	="Balance for first half current year"
	CY1COLL	="Collections for first half current year"
	CY1CR	="Credits Received from prior years"
	CY1FEE	="Fees for first half current year"
	CY1INT	="Interest for first half current year"
	CY1PEN	="Penalty for first half current year"
	CY1TAX	="Tax for first half current year"
	CY1TOTDUE	="Total due for first half current year"
	CY1TXSALE	="Tax sale flag for first half current year"
	CY1YEAR	="Year Description"
	CY2BAL	="Balance for second half current year"
	CY2COLL	="Collections for second half current year"
	CY2CR	="Credits Received from prior years"
	CY2FEE	="Fees for second half current year"
	CY2INT	="Interest for second half current year"
	CY2PEN	="Penalty for second half current year"
	CY2TAX	="Tax for second half current year"
	CY2TOTDUE	="Total due for second half current year"
	CY2TXSALE	="Tax sale flag for second half current year"
	CY2YEAR	="Year Description"
	DEED_DATE	="Date of deed"
	DEL_CODE	="Y= Dead N= Actice SSL"
	DUEDATE1	="First due date for bill"
	DUEDATE2	="Second due date for bill"
	DUEDATE3	="Third due date for bill"
	EXTRACTDAT	="Date of last extraction from database"
	HIGHNUMBER	="Ending House number of the property if it includes multiple addresses"
	HSTD_CODE	="Homestead flag: 1 = HS   2= Senior"
	INST_NO	="Instrument number of most recent Deed"
	LANDAREA	="Square footage of land per surveyor"
	LASTPAYDT	="Date of last payment received for the property"
	LOT	="Lot of Property"
	LOWNUMBER	="Base House Number of the property address"
	MIX1BLDPCT	="Percentage of the improvements affected by the first use code"
	MIX1BLDVAL	="Value of the improvements affected by the first use code"
	MIX1CLASS	="Tax class of first mix"
	MIX1LNDPCT	="Percentage of the land affected by the first use type"
	MIX1LNDVAL	="Value of the land affected by the first use type"
	MIX1RATE	="Tax rate for first mix, blank if not mixed use"
	MIX1TXTYPE	="Tax type one, also displays if there are any types of exemptions"
	MIX2BLDPCT	="If mixed use, the percentage of the improvements affected by the second mixed use, otherwise blank"
	MIX2BLDVAL	="If mixed use, the value of the improvements affected by the second mixed use, otherwise blank"
	MIX2CLASS	="If mixed useor part and part , the second tax class of the mixed use, otherwise blank"
	MIX2LNDPCT	="If mixed use, the percentage of land affected by the second mixed use, otherwise blank"
	MIX2LNDVAL	="If mixed use, the value of land affected by the second mixed use, otherwise blank"
	MIX2RATE	="If mixed use, the second tax rate of the mixed use, otherwise blank"
	MIX2TXTYPE	="If mixed use or part and part , the second tax type of the mixed use, otherwise blank"
	MORTGAGECO	="Mortgage key number"
	NBHD	="Assessor's Neighborhood Code"
	NBHDNAME	="Assessor's Neighborhood name"
	NEW_IMPR	="Proposed Build"
	NEW_LAND	="Proposed Land"
	NEW_TOTAL	="Proposed Total"
	NO_OWNOCCT	="# of occupied co-op units"
	NO_UNITS	="# of available co-op units"
	OLD_IMPR	="Prior Year Build"
	OLD_LAND	="Prior Year Land"
	OLD_TOTAL	="=Prior year Total"
	OWNERNAME	="Property Owners Name"
	PART_PART	="Y= Yes N= Not part and part"
	PCHILDCODE	="Refers to Child Lot: 2= Vacant  3= Garage otherwise blank"
	PHASEBUILD	="Currecnt Build"
	PHASELAND	="Current Land"
	PREMISEADD	="Property address string excluding city and zip code"
	PRMS_WARD	="City ward the the property is within"
	PROPTYPE	="Type of property, obtained from use code"
	PY10BAL	="Balance for prior year 1"
	PY10COLL	="Collections for prior year 10"
	PY10CR	="Credits Received from prior years"
	PY10FEE	="Fees for prior year 10"
	PY10INT	="Interest for prior year 10"
	PY10PEN	="Penalty for prior year 10"
	PY10TAX	="Tax for prior year 10"
	PY10TOTDUE	="Total due for prior year 10"
	PY10TXSALE	="Tax sale flag for prior year 10"
	PY10YEAR	="Year Description"
	PY1BAL	="Balance for prior year 1"
	PY1COLL	="Collections for prior year 1"
	PY1CR	="Credits Received from prior years"
	PY1FEE	="Fees for prior year 1"
	PY1INT	="Interest for prior year 1"
	PY1PEN	="Penalty for prior year 1"
	PY1TAX	="Tax for prior year 1"
	PY1TOTDUE	="Total due for prior year 1"
	PY1TXSALE	="Tax sale flag for prior year 1"
	PY1YEAR	="Year Description"
	PY2BAL	="Balance for prior year 2"
	PY2COLL	="Collections for prior year 2"
	PY2CR	="Credits Received from prior years"
	PY2FEE	="Fees for prior year 2"
	PY2INT	="Interest for prior year 2"
	PY2PEN	="Penalty for prior year 2"
	PY2TAX	="Tax for prior year 2"
	PY2TOTDUE	="Total due for prior year 2"
	PY2TXSALE	="Tax sale flag for prior year 2"
	PY2YEAR	="Year Description"
	PY3BAL	="Balance for prior year 3"
	PY3COLL	="Collections for prior year 3"
	PY3CR	="Credits Received from prior years"
	PY3FEE	="Fees for prior year 3"
	PY3INT	="Interest for prior year 3"
	PY3PEN	="Penalty for prior year 3"
	PY3TAX	="Tax for prior year 3"
	PY3TOTDUE	="Total due for prior year 3"
	PY3TXSALE	="Tax sale flag for prior year 3"
	PY3YEAR	="Year Description"
	PY4BAL	="Balance for prior year 4"
	PY4COLL	="Collections for prior year 4"
	PY4CR ="Credits Received from prior years"
	PY4FEE	="Fees for prior year 4"
	PY4INT	="Interest for prior year 4"
	PY4PEN	="Penalty for prior year 4"
	PY4TAX	="Tax for prior year 4"
	PY4TOTDUE	="Total due for prior year 4"
	PY4TXSALE	="Tax sale flag for prior year 4"
	PY4YEAR	="Year Description"
	PY5BAL	="Balance for prior year 5"
	PY5COLL	="Collections for prior year 5"
	PY5CR	="Credits Received from prior years"
	PY5CR	="Credits Received from prior years"
	PY5FEE	="Fees for prior year 5"
	PY5INT	="Interest for prior year 5"
	PY5PEN	="Penalty for prior year 5"
	PY5TAX	="Tax for prior year 5"
	PY5TOTDUE	="Total due for prior year 5"
	PY5TXSALE	="Tax sale flag for prior year 5"
	PY5YEAR	="Year Description"
	PY6BAL	="Balance for prior year 6"
	PY6COLL	="Collections for prior year 6"
	PY6CR	="Credits Received from prior years"
	PY6FEE	="Fees for prior year 6"
	PY6INT	="Interest for prior year 6"
	PY6PEN	="Penalty for prior year 6"
	PY6TAX	="Tax for prior year 6"
	PY6TOTDUE	="Total due for prior year 6"
	PY6TXSALE	="Tax sale flag for prior year 6"
	PY6YEAR	="Year Description"
	PY7BAL	="Balance for prior year 7"
	PY7COLL	="Collections for prior year 7"
	PY7CR	="Credits Received from prior years"
	PY7FEE	="Fees for prior year 7"
	PY7INT	="Interest for prior year 7"
	PY7PEN	="Penalty for prior year 7"
	PY7TAX	="Tax for prior year 7"
	PY7TOTDUE	="Total due for prior year 7"
	PY7TXSALE	="Tax sale flag for prior year 7"
	PY7YEAR	="Year Description"
	PY8BAL	="Balance for prior year 8"
	PY8COLL	="Collections for prior year 8"
	PY8CR	="Credits Received from prior years"
	PY8FEE	="Fees for prior year 8"
	PY8INT	="Interest for prior year 8"
	PY8PEN	="Penalty for prior year 8"
	PY8TAX	="Tax for prior year 8"
	PY8TOTDUE	="Total due for prior year 8"
	PY8TXSALE	="Tax sale flag for prior year 8"
	PY8YEAR	="Year Description"
	PY9BAL	="Balance for prior year 9"
	PY9COLL	="Collections for prior year 9"
	PY9CR	="Credits Received from prior years"
	PY9FEE	="Fees for prior year 9"
	PY9INT	="Interest for prior year 9"
	PY9PEN	="Penalty for prior year 9"
	PY9TAX	="Tax for prior year 9"
	PY9TOTDUE	="Total due for prior year 9"
	PY9TXSALE	="Tax sale flag for prior year 9"
	PY9YEAR	="Year Description"
	QDRNTNAME	="Quadrant name spelled out: NE,NW,SE or SW"
	SALEDATE	="Most recent property sale date"
	SALEPRICE	="Most recent property sale price"
	SALETYPE	="Type of property sale (single or multiple lot, etc.)"
	SQUARE	="Square of property"
	SSL	="Square, Suffix and Lot of property"
	STREETNAME	="Street name portion of the property address"
	SUB_NBHD	="Assessor's Sub-Neighborhood code"
	SUFFIX	="Suffix of property"
	TOTBALAMT	="Total balance due for property: all years"
	TOTCOLAMT	="Total of all collections: all years"
	TOTDUEAMT	="Total of all liabilities: all years"
	TRIGROUP	="Triennial Tax Assessment Group assignment"
	UNITNUMBER	="Unit number, typically associated with condominiums"
	USECODE	="Property Use Code"
	VACLNDUSE	="Y = Vacant N= Improved"

	/* Labels from DC Open data portal June 2022 */
	INTERNALID = "DC Open Data Internal ID"
	LAND_USE_CODE = "Land use code"
	LAND_USE_DESCRIPTION = "Land use description"
	LAST_SALE_PRICE = "Most recent property sale price"
	OTR_NEIGHBORHOOD_CODE = "Assessor's neighborhood code"
	OTR_NEIGHBORHOOD_NAME = "Assessor's neighborhood name"
	OWNER_ADDRESS_CITYSTZIP = "Owner address line 3"
	OWNER_ADDRESS_LINE1 = "Owner address line 1"
	OWNER_ADDRESS_LINE2 = "Owner address line 2"
	OWNER_NAME_PRIMARY = "Primary owner name"
	OWNER_NAME_SECONDARY = "Name of second primary owner"
	PACEBALANCE = "Balance Due for Property Assessed Clean Energy Fee, if applicable"
	PACECOLLECTED = "Total Amount Collected for Property Assessed Clean Energy Fee, if applicable"
	PACETOTALDUE = "Total Amount Due for Property Assessed Clean Energy Fee, if applicable"
	PARTPART = "Y = Yes N = Not part and part"
	PIPARENTLOT = "Square, Suffix, Lot of the property that the Possessory Interest is associated to"
	PRESSL = "Going forward, this will record the Square, Suffix, Lot of the lot that it was created from"
	PROPERTY_ADDRESS = "Property address string excluding city and zip code"
	PROPOSED_ASSESSMENT_CAP = "Cap assessment for proposed year"
	QUALIFIED = "Q is for a single-parcel sale considered to be a valid, arms-length market sale by the AD."
	ROW_NUMBER = "Sequence number to maintain sort order. Sort order is SSL (a), sale date (d), recordation instrument order (d)."
	SALE_CODE = "Sales codes. Single-parcel sale codes are numeric, when preceded by an “M” the sale is for multiple parcels"
	SALE_CURR_OWNER = "Indicates data is for current owner"
	SALE_DATE = "Date on which the sale was recorded among the District of Columbia’s land records."
	SALE_PRICE = "Generally, represents the amount paid. For historic sale data, price is always > $0. For current owner sale price may be null or $0."
	SEWSBALANCE = "Balance Due for Southeast Water and Sewer, if applicable"
	SEWSCOLLECTED = "Total Amount Collected for Southeast Water and Sewer, if applicable"
	SEWSTOTALDUE = "Total Amount Due for Southeast Water and Sewer, if applicable"
	SWWSADBALANCE = "Balance Due for Southwest Waterfront Special Assessment District, if applicable"
	SWWSADCOLLECTED = "Total Amount Collected for Southwest Waterfront Special Assessment District, if applicable"
	SWWSADTOTALDUE = "Total Amount Due for Southwest Waterfront Special Assessment District, if applicable"
	TAX_TYPE_DESCRIPTION = "Tax type description"
	VACANT_USE = "YES = Vacant; NO = Improved"
	ADDRESS_ID = "Internal address identifier"
	APPRAISED_VALUE_PROPOSED_IMPR = "Proposed building value"
	APPRAISED_VALUE_PROPOSED_LAND = "Proposed land value"
	APPRAISED_VALUE_PROPOSED_TOTAL ="Proposed total value"
	BIDBALANCE = "Balance Due for BID dues, if applicable"
	BIDCOLLECTED = "Total Amount Collected for BID dues, if applicable"
	BIDNAME = "Name of neighborhood BID"
	BIDTOTALDUE = "Total Amount Due for BID dues, if applicable"
	CURRENT_ASSESSMENT_CAP = "Cap assessment for current year"
	GIS_LAST_MOD_DTTM = "Timestamp for last data modification"
	HOMESTEAD_DESCRIPTION = "Homestead description"
	
;

